### PR TITLE
Add polish translation.

### PR DESCRIPTION
**Pull request by Sopel97**

### CODE REVIEW

**Comment by Aloril** [comment]
Need "_lan":"pol", line, see https://github.com/TCEC-Chess/tcecgui/blob/master/translate/bul.json#L2

**Comment by Sopel97** [comment]
looks like there was also a need for a rebase. done

**Comment by Aloril** [comment]
Should this be lowercase 'polski'?
pol: 'Polski',

**Comment by Aloril** [comment]
Added it already, can fix this later if needed.

**Pull request merged**
